# coding: utf-8

# flake8: noqa
"""
    Kagi API

    The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 

    The version of the OpenAPI document: 1
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.error_detail import ErrorDetail
from openapi_client.models.error_envelope import ErrorEnvelope
from openapi_client.models.extract_request import ExtractRequest
from openapi_client.models.extract_response import ExtractResponse
from openapi_client.models.meta import Meta
from openapi_client.models.page_input import PageInput
from openapi_client.models.page_output import PageOutput
from openapi_client.models.search200_response import Search200Response
from openapi_client.models.search200_response_data import Search200ResponseData
from openapi_client.models.search_request import SearchRequest
from openapi_client.models.search_request_extract import SearchRequestExtract
from openapi_client.models.search_request_filters import SearchRequestFilters
from openapi_client.models.search_request_lens import SearchRequestLens
from openapi_client.models.search_request_personalizations import SearchRequestPersonalizations
from openapi_client.models.search_request_personalizations_domains_inner import SearchRequestPersonalizationsDomainsInner
from openapi_client.models.search_request_personalizations_regexes_inner import SearchRequestPersonalizationsRegexesInner
from openapi_client.models.search_result import SearchResult
from openapi_client.models.search_result_image import SearchResultImage

