# coding: utf-8

# flake8: noqa

"""
    Kagi API

    The Kagi API provides programmatic access to data that powers our search results & more.   Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more.  ### Official Client Libraries  We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library.  - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust)  ### API Status  **The v1 API is currently in preview to early access testers.**  Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available.  See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details.  ### Pricing  See our [API Pricing](https://kagi.com/api/pricing) page for standard rates.  ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas)  ### Discord  Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs! 

    The version of the OpenAPI document: 1
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ExtractApi",
    "SearchApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ErrorDetail",
    "ErrorEnvelope",
    "ExtractRequest",
    "ExtractResponse",
    "Meta",
    "PageInput",
    "PageOutput",
    "Search200Response",
    "Search200ResponseData",
    "SearchRequest",
    "SearchRequestExtract",
    "SearchRequestFilters",
    "SearchRequestLens",
    "SearchRequestPersonalizations",
    "SearchRequestPersonalizationsDomainsInner",
    "SearchRequestPersonalizationsRegexesInner",
    "SearchResult",
    "SearchResultImage",
]

# import apis into sdk package
from openapi_client.api.extract_api import ExtractApi as ExtractApi
from openapi_client.api.search_api import SearchApi as SearchApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.error_detail import ErrorDetail as ErrorDetail
from openapi_client.models.error_envelope import ErrorEnvelope as ErrorEnvelope
from openapi_client.models.extract_request import ExtractRequest as ExtractRequest
from openapi_client.models.extract_response import ExtractResponse as ExtractResponse
from openapi_client.models.meta import Meta as Meta
from openapi_client.models.page_input import PageInput as PageInput
from openapi_client.models.page_output import PageOutput as PageOutput
from openapi_client.models.search200_response import Search200Response as Search200Response
from openapi_client.models.search200_response_data import Search200ResponseData as Search200ResponseData
from openapi_client.models.search_request import SearchRequest as SearchRequest
from openapi_client.models.search_request_extract import SearchRequestExtract as SearchRequestExtract
from openapi_client.models.search_request_filters import SearchRequestFilters as SearchRequestFilters
from openapi_client.models.search_request_lens import SearchRequestLens as SearchRequestLens
from openapi_client.models.search_request_personalizations import SearchRequestPersonalizations as SearchRequestPersonalizations
from openapi_client.models.search_request_personalizations_domains_inner import SearchRequestPersonalizationsDomainsInner as SearchRequestPersonalizationsDomainsInner
from openapi_client.models.search_request_personalizations_regexes_inner import SearchRequestPersonalizationsRegexesInner as SearchRequestPersonalizationsRegexesInner
from openapi_client.models.search_result import SearchResult as SearchResult
from openapi_client.models.search_result_image import SearchResultImage as SearchResultImage

